reld: elf/x86_64/gotpcrelx-jump/malfunction-no-jmp-indirect-to-relative/gotpcrelx-jump.s.reld
ld: elf/x86_64/gotpcrelx-jump/malfunction-no-jmp-indirect-to-relative/gotpcrelx-jump.s.ld
rel.missing-opt.R_X86_64_GOTPCRELX.JmpIndirectToRelative.static-non-pie
`elf/x86_64/gotpcrelx-jump/malfunction-no-jmp-indirect-to-relative/gotpcrelx-jump.s.o` .text _start
R_X86_64_GOTPCRELX
ORIG target -4
R_X86_64_GOTPCRELX NoOp
reld GOT->target
reld TRACE: relocation applied flags=NON_INTERPOSABLE | DIRECT | GOT,
reld TRACE: rel_kind=GotRelative,
R_X86_64_PC32 JmpIndirectToRelative
ld   target

