//! This crate defines a format for providing information about where a linker put stuff.

use anyhow::Context;
use anyhow::Result;
use serde::Deserialize;
use serde::Serialize;
use std::io::Write;
use std::ops::Range;
use std::path::Path;
use std::path::PathBuf;

#[derive(Serialize, Deserialize, PartialEq, Eq, Debug, Default)]
pub struct Metrics {
    /// Total number of range-extension thunks allocated across all input objects.
    pub thunk_count: u64,
}

#[derive(Serialize, Deserialize, PartialEq, Eq, Debug)]
pub struct Layout {
    /// Object format of the linked image. Consumers must dispatch on this field instead of
    /// assuming ELF when interpreting contribution addresses.
    pub format: BinaryFormat,

    /// The input files to the linker.
    pub files: Vec<InputFile>,

    /// Metrics collected during linking.
    #[serde(default)]
    pub metrics: Metrics,
}

#[derive(Serialize, Deserialize, PartialEq, Eq, Debug, Clone, Copy, Default)]
pub enum BinaryFormat {
    #[default]
    Elf,
    Coff,
    MachO,
}

#[derive(Serialize, Deserialize, PartialEq, Eq, Debug)]
pub struct InputFile {
    /// Stable zero-based object index used by COFF contribution records and diagnostics.
    pub object_index: u32,

    /// Path to the input file on disk. In case of archives, multiple inputs may have the same
    /// path.
    pub path: PathBuf,

    /// If the input is an archive, then contains information about where in the archive the file
    /// came from.
    pub archive_entry: Option<ArchiveEntryInfo>,

    /// Sections that were written to the output. Indexes correspond to the sections in the input
    /// file. Contains None for sections that were discarded or weren't fully copied.
    pub sections: Vec<Option<Section>>,

    /// The file was a temporary file, most likely generated by a linker plugin. Absence of the
    /// file should not be treated as an error.
    pub temporary: bool,
}

#[derive(Serialize, Deserialize, PartialEq, Eq, Debug, Clone)]
pub struct ArchiveEntryInfo {
    /// The range within the file that contains the archive entry (not including the entry header).
    pub range: Range<usize>,

    pub identifier: Vec<u8>,
}

#[derive(Serialize, Deserialize, PartialEq, Eq, Debug)]
pub struct Section {
    /// Zero-based input section index in the object file.
    pub input_section_index: u32,

    /// Name of the output section (ELF/COFF) or segment+section pair (Mach-O).
    pub output_section: String,

    /// Format-neutral description of where this contribution was placed.
    pub address: ContributionAddress,

    /// Legacy absolute-address view used by the ELF relocation differ.
    pub mem_range: Range<u64>,
}

#[derive(Serialize, Deserialize, PartialEq, Eq, Debug, Clone)]
pub enum ContributionAddress {
    /// ELF virtual-address range.
    VirtualAddress(Range<u64>),
    /// PE/COFF RVA range. Together with InputFile::object_index and Section::input_section_index,
    /// this is a complete COFF contribution record.
    RelativeVirtualAddress(Range<u32>),
    /// Mach-O contribution within a named segment.
    SegmentOffset { segment: String, range: Range<u64> },
}

impl Layout {
    pub fn write(&self, writer: &mut impl Write) -> Result<()> {
        postcard::to_io(self, writer)?;
        Ok(())
    }

    pub fn to_bytes(&self) -> Result<Vec<u8>> {
        Ok(postcard::to_stdvec(self)?)
    }

    pub fn from_bytes(bytes: &[u8]) -> Result<Self> {
        postcard::from_bytes(bytes).context("Invalid linker layout")
    }
}

#[must_use]
pub fn layout_path(base_path: &Path) -> PathBuf {
    // We always want to append, not use with_extension, since we don't want to remove any existing
    // extension, otherwise we'd likely get collisions.
    let mut s = base_path.as_os_str().to_owned();
    s.push(".layout");
    PathBuf::from(s)
}

impl std::fmt::Display for InputFile {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.path.display().fmt(f)?;
        if let Some(e) = self.archive_entry.as_ref() {
            write!(f, " @ {}", String::from_utf8_lossy(&e.identifier))?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_round_trip() {
        let layout = Layout {
            format: BinaryFormat::Elf,
            files: vec![InputFile {
                object_index: 0,
                path: PathBuf::new(),
                archive_entry: None,
                sections: vec![Some(Section {
                    input_section_index: 0,
                    output_section: ".text".to_owned(),
                    address: ContributionAddress::VirtualAddress(42..48),
                    mem_range: 42..48,
                })],
                temporary: true,
            }],
            metrics: Metrics { thunk_count: 3 },
        };
        let bytes = layout.to_bytes().unwrap();
        let layout2 = Layout::from_bytes(&bytes).unwrap();
        assert_eq!(layout, layout2);
    }

    #[test]
    fn represents_coff_and_macho_contributions() {
        let coff = ContributionAddress::RelativeVirtualAddress(0x1000..0x1020);
        let macho = ContributionAddress::SegmentOffset {
            segment: "__TEXT".to_owned(),
            range: 0x40..0x60,
        };
        assert_ne!(coff, macho);
    }
}
